### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by tman10001** [momentumdevelopment/momentum#49]
* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.9/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap

**Comment by pastimee** [comment]
your computer doesn't have enough storage space

**Comment by tman10001** [comment]
my pc has 164gb free space

**Comment by pastimee** [comment]
don't know then, maybe a gradle inconsistency?

**Comment by sixtieth2** [comment]
your iq is too low so it failed
